# Generated by Django 5.1.1 on 2024-12-13 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('damage', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('cooldown_time', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('energy_level', models.IntegerField(default=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('energy_max', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttackHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_spent', models.IntegerField()),
                ('damage_done', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicka.powerability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('energy_level', models.IntegerField(default=100)),
                ('energy_max', models.IntegerField(default=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicka.powerability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
